context_size: 7
feature_dim: 40
frame_shift: 160
frame_size: 400
input_transform: logmel_meannorm
macro_batchsize: 1
min_length: 0
num_frames: 3600
num_speakers: 10
num_workers: 16
sampling_rate: 16000
seed: 23
specaugment: False
subsampling: 10
use_last_samples: True
time_shuffle: False
train_data_dir: /workspace/benchmarks/amiheadset/train_kaldi
valid_data_dir: /workspace/benchmarks/amiheadset/dev_kaldi
features_output_path: /workspace/benchmarks/amiheadset/features_f3600